-- Demo PostgreSQL schema for pg-meta-doc.
-- The postgres Docker entrypoint runs this file on first container startup.

CREATE TABLE departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT REFERENCES departments(department_id),
    name TEXT,
    email TEXT NOT NULL,
    created_at TIMESTAMP,
    usr_id BIGINT,
    users_id BIGINT
);

CREATE UNIQUE INDEX ux_users_email ON users(email);
CREATE INDEX idx_users_department_id ON users(department_id);

CREATE TABLE profiles (
    id BIGINT,
    user_id BIGINT PRIMARY KEY REFERENCES users(id),
    display_name TEXT,
    bio TEXT
);

CREATE TABLE audit_logs (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    entity_id BIGINT,
    created_at TIMESTAMP,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb
);

INSERT INTO departments (name, code) VALUES
    ('Engineering', 'eng'),
    ('Support', 'sup'),
    ('Finance', 'fin');

INSERT INTO users (department_id, name, email, created_at, usr_id, users_id) VALUES
    (1, 'Ada Lovelace', 'ada@example.test', now() - interval '10 days', NULL, NULL),
    (1, NULL, 'grace@example.test', NULL, 1, 1),
    (2, 'Katherine Johnson', 'katherine@example.test', now() - interval '3 days', NULL, NULL),
    (3, 'Mary Jackson', 'mary@example.test', now() - interval '1 day', 2, 2);

INSERT INTO profiles (id, user_id, display_name, bio) VALUES
    (1001, 1, 'Ada', 'First demo profile'),
    (1002, 2, 'Grace', 'Profile with a non-primary id column'),
    (1003, 3, 'Katherine', NULL);

INSERT INTO audit_logs (user_id, entity_id, created_at, payload)
SELECT
    ((series_number - 1) % 4) + 1,
    ((series_number - 1) % 3) + 1,
    now() - (series_number || ' minutes')::interval,
    jsonb_build_object(
        'action',
        CASE
            WHEN series_number % 3 = 0 THEN 'create'
            WHEN series_number % 3 = 1 THEN 'update'
            ELSE 'view'
        END,
        'sequence',
        series_number
    )
FROM generate_series(1, 1200) AS series(series_number);

ANALYZE;
